# Generated by Django 4.2.15 on 2024-08-10 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_address_street_alter_wallet_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_chain',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
