# Generated by Django 4.2.15 on 2024-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chain_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
