# Generated by Django 4.2.15 on 2024-08-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_chain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chain_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
